model_meta:
  name: lp_proxy
  pclass: optimization
  ptype: lp
  architecture: feedforward
  activation: relu
  check: constraint
  engine: milp
  report: yes
layers:
- weights:
  - - -0.19689548015594482
    - -0.2703263461589813
  - - 0.5977350473403931
    - 0.007955772802233696
  - - 0.4005013406276703
    - 0.36681804060935974
  - - -0.7005499601364136
    - -0.5247310400009155
  - - -0.4564168155193329
    - 0.38940131664276123
  - - 0.3627365529537201
    - 0.6921821236610413
  - - -0.43703144788742065
    - -0.5225429534912109
  - - -0.06418031454086304
    - -0.31231775879859924
  - - 0.3054978847503662
    - 0.7191721796989441
  - - 0.5445215702056885
    - 0.1987650841474533
  - - -0.24759218096733093
    - 0.45941394567489624
  - - 0.7224196195602417
    - -0.3042128384113312
  - - 0.7330524921417236
    - 0.6303262114524841
  - - 0.007664322853088379
    - -0.6991412043571472
  - - -0.6454477906227112
    - -0.3999093472957611
  - - -0.3014083802700043
    - 0.7036214470863342
  biases:
  - -0.4999750852584839
  - -0.6702486872673035
  - 0.5254024267196655
  - 0.21062254905700684
  - -0.06651090085506439
  - -0.37620478868484497
  - 0.22915440797805786
  - -0.5670956373214722
  - 0.6347167491912842
  - 0.3071950078010559
  - 0.46108412742614746
  - 0.18735381960868835
  - 0.47241175174713135
  - 0.5840075612068176
  - -0.2063692808151245
  - -0.35136014223098755
- weights:
  - - -0.16274166107177734
    - 0.23695024847984314
    - -0.16632476449012756
    - -0.17066878080368042
    - -0.08946859836578369
    - 0.09369206428527832
    - -0.10963553190231323
    - -0.10952973365783691
    - -0.11587226390838623
    - -0.22544068098068237
    - -0.2208094298839569
    - -0.21195244789123535
    - 0.04128497838973999
    - 0.14404505491256714
    - 0.0226040780544281
    - -0.10800546407699585
  - - 0.056368470191955566
    - -0.27717718482017517
    - -0.25973278284072876
    - 0.06392061710357666
    - -0.003041521878913045
    - 0.11623945087194443
    - -0.014116078615188599
    - 0.026948243379592896
    - 0.08230689913034439
    - 0.04425922781229019
    - -0.28847774863243103
    - 0.03722801432013512
    - 0.01624498888850212
    - 0.16871953010559082
    - 0.10771185159683228
    - -0.27399134635925293
  - - 0.054645031690597534
    - 0.32251232862472534
    - 0.26923686265945435
    - 0.2340850532054901
    - 0.05521177127957344
    - -0.08253809809684753
    - -0.21117720007896423
    - -0.21329766511917114
    - 0.33064064383506775
    - 0.294188916683197
    - 0.12111593037843704
    - 0.04203321784734726
    - 0.3294948935508728
    - 0.1336006224155426
    - -0.001545041799545288
    - 0.32649341225624084
  - - -0.1972944736480713
    - 0.06404739618301392
    - 0.027879774570465088
    - -0.04142254590988159
    - 0.008475542068481445
    - 0.22877603769302368
    - -0.14310070872306824
    - -0.17937549948692322
    - -0.24162200093269348
    - -0.009209096431732178
    - -0.2103610634803772
    - -0.006118208169937134
    - -0.2238127887248993
    - -0.1568523347377777
    - 0.07876008749008179
    - -0.11468121409416199
  - - -0.06818148493766785
    - -0.0912984311580658
    - 0.035898253321647644
    - -0.11958575248718262
    - -0.1774572730064392
    - -0.19834403693675995
    - 0.24510571360588074
    - 0.06261321902275085
    - 0.08384301513433456
    - -0.0914493203163147
    - -0.2248409390449524
    - -0.26193711161613464
    - 0.16042231023311615
    - -0.19853782653808594
    - -0.031889647245407104
    - -0.31341105699539185
  - - 0.23386141657829285
    - 0.5056115984916687
    - 0.29323750734329224
    - -0.20483556389808655
    - 0.21087244153022766
    - 0.37429574131965637
    - 0.16273820400238037
    - 0.2067505419254303
    - 0.38052287697792053
    - -0.050153423100709915
    - 0.04279103875160217
    - 0.3235374987125397
    - 0.27211639285087585
    - -0.1446283757686615
    - -0.03851038217544556
    - 0.4090093672275543
  - - 0.16064861416816711
    - 0.3748222291469574
    - 0.20122405886650085
    - -0.18115925788879395
    - 0.10634457319974899
    - 0.3747790455818176
    - 0.030811220407485962
    - -0.24013552069664001
    - -0.013723833486437798
    - 0.2838912308216095
    - 0.2080027312040329
    - 0.06554194539785385
    - 0.05636441707611084
    - 0.184864342212677
    - 0.23295074701309204
    - 0.4075195789337158
  - - 0.13471201062202454
    - 0.011952340602874756
    - -0.09138557314872742
    - -0.09972906112670898
    - 0.05013304948806763
    - 0.0035904347896575928
    - 0.06519976258277893
    - 0.05096021294593811
    - -0.22148343920707703
    - -0.24734574556350708
    - 0.0209541916847229
    - -0.11591294407844543
    - -0.19516664743423462
    - 0.002908945083618164
    - -0.23537668585777283
    - 0.08609485626220703
  - - 0.05808645486831665
    - -0.6163689494132996
    - 0.286586731672287
    - 0.11162164807319641
    - 0.43430161476135254
    - -0.10527782887220383
    - -0.030802547931671143
    - 0.21026447415351868
    - 0.010293316096067429
    - 0.0017062538536265492
    - 0.266923725605011
    - 0.18684591352939606
    - -0.05355570465326309
    - -0.1724444031715393
    - 0.15058541297912598
    - -0.00739478413015604
  - - -0.10294070839881897
    - 0.13028688728809357
    - -0.0486946627497673
    - -0.12847375869750977
    - -0.0019895380828529596
    - -0.046026673167943954
    - 0.12212100625038147
    - 0.15930110216140747
    - 0.0540156364440918
    - 0.018468013033270836
    - 0.2503947615623474
    - -0.0262835044413805
    - 0.409540593624115
    - 0.06680738925933838
    - -0.24713972210884094
    - 0.0022240548860281706
  - - -0.07255730032920837
    - 0.17439505457878113
    - -0.17893248796463013
    - -0.22023144364356995
    - 0.12334516644477844
    - 0.03573611378669739
    - -0.16310587525367737
    - -0.03175222873687744
    - 0.10038191080093384
    - 0.18450507521629333
    - -0.005400121212005615
    - -0.059948474168777466
    - -0.15758103132247925
    - -0.17153441905975342
    - 0.11672276258468628
    - -0.025962650775909424
  - - -0.16262662410736084
    - -0.28824397921562195
    - -0.0033203372731804848
    - -0.012075453996658325
    - -0.26864585280418396
    - 0.05396343767642975
    - 0.1658044159412384
    - 0.1622878611087799
    - -0.1238078847527504
    - -0.017819536849856377
    - 0.012956686317920685
    - 0.03599622845649719
    - -0.0071390727534890175
    - -0.13730022311210632
    - -0.10486757755279541
    - 0.14402127265930176
  - - 0.01809665560722351
    - 0.11714033782482147
    - 0.04780450463294983
    - 0.08456122875213623
    - -0.17524677515029907
    - 0.32719215750694275
    - 0.24547752737998962
    - 0.16416266560554504
    - 0.170555979013443
    - -0.07625932991504669
    - 0.28258615732192993
    - 0.2925410270690918
    - 0.20288711786270142
    - -0.026553213596343994
    - -0.031620025634765625
    - 0.14353998005390167
  - - 0.1981258988380432
    - -0.023137390613555908
    - -0.23494917154312134
    - 0.040302127599716187
    - 0.16226518154144287
    - 0.046965450048446655
    - 0.12938395142555237
    - 0.0846133828163147
    - -0.22910717129707336
    - 0.24700450897216797
    - 0.09977689385414124
    - -0.14300960302352905
    - -0.24174770712852478
    - 0.24918818473815918
    - -0.1598559021949768
    - 0.07005360722541809
  - - 0.16104120016098022
    - 0.08300195634365082
    - -0.14365282654762268
    - -0.05837935209274292
    - 0.22383981943130493
    - 0.216200590133667
    - -0.14222058653831482
    - 0.18040254712104797
    - -0.06249821186065674
    - -0.053572218865156174
    - -0.18015998601913452
    - 0.10346457362174988
    - -0.09056660532951355
    - 0.0024280846118927
    - 0.008488774299621582
    - 0.035918623208999634
  - - 0.09331929683685303
    - -0.07181590795516968
    - -0.1833265721797943
    - 0.237748384475708
    - 0.09113410115242004
    - -0.13600222766399384
    - -0.06984323263168335
    - -0.2470703125
    - -0.10412658751010895
    - 0.20083492994308472
    - 0.08769295364618301
    - -0.19141820073127747
    - 0.14672398567199707
    - -0.12819117307662964
    - 0.19506952166557312
    - -0.2595840096473694
  biases:
  - 0.04008355736732483
  - -0.11861865222454071
  - -0.09133107215166092
  - -0.1175355613231659
  - -0.12298878282308578
  - 0.18287305533885956
  - -0.027601486071944237
  - 0.12326827645301819
  - 0.26414528489112854
  - 0.3496333956718445
  - -0.02665427327156067
  - 0.120118148624897
  - 0.33945417404174805
  - 0.10014179348945618
  - 0.13835673034191132
  - -0.07912462204694748
- weights:
  - - -0.02770891785621643
    - -0.010470042936503887
    - 0.1085054874420166
    - -0.029271990060806274
    - -0.03263923153281212
    - -0.06124117225408554
    - -0.02790016122162342
    - -0.12867367267608643
    - -0.00717189209535718
    - 0.19691571593284607
    - -0.2310459017753601
    - -0.2608184516429901
    - -0.1250065267086029
    - -0.2007993459701538
    - 0.16723139584064484
    - -0.08300893008708954
  - - -0.01315373182296753
    - -0.19513826072216034
    - 0.3387916088104248
    - 0.01813676953315735
    - -0.16861458122730255
    - 0.13559174537658691
    - 0.3639160990715027
    - 0.11246630549430847
    - -0.4828020930290222
    - 0.3464580476284027
    - 0.09405457973480225
    - -0.1075654923915863
    - 0.3891688585281372
    - -0.2271583080291748
    - -0.056323982775211334
    - -0.027422547340393066
  - - -0.034624695777893066
    - 0.1839245855808258
    - -0.18138697743415833
    - -0.08933761715888977
    - -0.18613804876804352
    - 0.08754357695579529
    - 0.0007332190289162099
    - -0.13377666473388672
    - 0.010887709446251392
    - 0.005568868014961481
    - -0.18830397725105286
    - 0.21991845965385437
    - 0.08939849585294724
    - 0.0851205587387085
    - 0.2161930799484253
    - -0.10933554917573929
  - - -0.15729153156280518
    - 0.051512476056814194
    - 0.10809260606765747
    - 0.23741862177848816
    - 0.18038618564605713
    - -0.06738848984241486
    - -0.038426000624895096
    - 0.08482033014297485
    - 0.009529794566333294
    - -0.06741616874933243
    - 0.11439302563667297
    - 0.0641164630651474
    - 0.060752201825380325
    - 0.22869977355003357
    - -0.147482231259346
    - 0.12403259426355362
  biases:
  - -0.08538053184747696
  - 0.11895167827606201
  - -0.019859829917550087
  - -0.023381391540169716
verification_spec:
  input_bounds:
  - min: 0
    max: 5
  - min: 0
    max: 5
  indices:
    input_indices:
    - 0
    - 1
    output_indices:
    - 2
    - 3
    - 4
    - 5
  constraints:
    A:
    - - -0.4168082379831586
      - 0.10701540134806642
      - -0.6756982427995801
      - -0.7487797948924007
      - -0.6881593278834714
      - -0.38256195237334456
    - - 0.38158208067245725
      - 0.8124296454659361
      - 0.39966756990200114
      - 0.22309366411081388
      - 0.124275177078637
      - -0.9499362860823835
    - - -0.3416653763580384
      - 0.3180480198026645
      - -0.5624616463693841
      - -0.13567133060160708
      - -0.32794363151481676
      - -0.2396588713974388
    - - -0.931118400928518
      - -0.5395042318409635
      - 0.7601913981040291
      - 0.6691246681695915
      - -0.5570356813211428
      - -0.30205177947309525
    - - 1.0
      - 1.0
      - -1.0
      - -1.0
      - -1.0
      - -1.0
    b_static:
    - 7.9843584587919025
    - 9.482164196472976
    - 6.447403490044
    - 7.9299018032758175
    - 0.0
  objective_c:
  - 0.0
  - 0.0
  - 0.6393608232364495
  - 0.16880196745330905
  - 0.994923988199265
  - 0.2662999449958718
