model_meta:
  name: lp_proxy
  pclass: optimization
  ptype: lp
  architecture: feedforward
  activation: relu
  check: constraint
  engine: milp
  report: yes


verification_spec:
  input_bounds:
  - min: 0
    max: 5
  - min: 0
    max: 5
  indices:
    input_indices:
    - 0
    - 1
    output_indices:
    - 2
    - 3
  constraints:
    A:
    - - -0.4168082379831586
      - 0.10701540134806642
    - - 0.38158208067245725
      - 0.8124296454659361
    - - -0.3416653763580384
      - 0.3180480198026645
    - - -0.931118400928518
      - -0.5395042318409635
    - - 1.0
      - 1.0
    b_static:
    - 7.9843584587919025
    - 9.482164196472976
  objective_c:
  - 0.994923988199265
  - 0.2662999449958718


layers:
- weights:
  - - -0.19689548015594482
    - -0.2703263461589813
  - - 0.5977350473403931
    - 0.007955772802233696
  biases:
  - -0.4999750852584839
  - -0.6702486872673035
  - 0.5254024267196655
  - 0.21062254905700684
- weights:
  - - -0.19689548015594482
    - -0.2703263461589813
  - - 0.5977350473403931
    - 0.007955772802233696
  biases:
  - -0.4999750852584839
  - -0.6702486872673035
  - 0.5254024267196655
  - 0.21062254905700684


